"""Static reference text for passive checks: category, CWE, OWASP Top 10:2025, WSTG v4.2 id,
description, developer impact, and remediation. Severity and confidence are computed dynamically
by each plugin from the actual response and page context, never read from this table.

User-facing text (title, category, description, developer_impact, remediation) is authored in
Brazilian Portuguese since it is rendered directly on the site. CWE/OWASP/WSTG identifiers stay
in English, matching how these international standards are referenced in Brazilian practice.
"""

CATALOG: dict[str, dict[str, str]] = {
    "transport.https": {
        "title": "Conexão não é criptografada",
        "category": "Segurança de Transporte",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "A página foi obtida via HTTP simples em vez de HTTPS.",
        "developer_impact": "Qualquer pessoa no caminho de rede pode ler ou modificar requisições e respostas, incluindo credenciais e cookies de sessão.",
        "remediation": "Redirecione toda requisição HTTP para HTTPS e configure um certificado TLS válido.",
    },
    "tls.legacy_protocol": {
        "title": "Protocolo TLS obsoleto em uso",
        "category": "Segurança de Transporte",
        "cwe": "CWE-326",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "O servidor negociou uma versão de TLS descontinuada.",
        "developer_impact": "Versões antigas do TLS contêm fraquezas de design conhecidas e podem violar diretrizes de conformidade atuais.",
        "remediation": "Configure o servidor para permitir apenas TLS 1.2 e TLS 1.3.",
    },
    "tls.certificate_expiry": {
        "title": "Certificado TLS expira em breve",
        "category": "Segurança de Transporte",
        "cwe": "CWE-298",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "O tempo restante de validade do certificado TLS é curto.",
        "developer_impact": "Um certificado expirado gera avisos no navegador e pode tornar a aplicação indisponível.",
        "remediation": "Automatize a renovação do certificado e configure alertas antes que a validade restante chegue a 30 dias.",
    },
    "headers.hsts_missing": {
        "title": "Navegador pode ser rebaixado para HTTP",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CONF-07",
        "description": "A resposta HTTPS não envia o cabeçalho Strict-Transport-Security.",
        "developer_impact": "Uma primeira visita, ou um link digitado como http://, ainda pode ser interceptado antes que o redirecionamento para HTTPS ocorra.",
        "remediation": "Nas respostas HTTPS, adicione `Strict-Transport-Security: max-age=31536000; includeSubDomains` após validar todos os subdomínios.",
    },
    "headers.hsts_weak": {
        "title": "Política de HSTS é muito curta",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CONF-07",
        "description": "Strict-Transport-Security está presente, mas seu max-age é curto.",
        "developer_impact": "Um max-age curto oferece proteção contra downgrade apenas por pouco tempo, reexpondo os usuários entre visitas.",
        "remediation": "Após validar a cobertura HTTPS, aumente o max-age do HSTS para pelo menos 31536000 segundos.",
    },
    "headers.csp_missing": {
        "title": "Navegador não possui política de execução de conteúdo",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Nenhum cabeçalho Content-Security-Policy foi retornado.",
        "developer_impact": "Scripts injetados têm menos restrições em nível de navegador, aumentando o impacto de qualquer falha de XSS.",
        "remediation": "Comece com uma Content-Security-Policy em modo somente-relatório, inventarie as origens necessárias e depois aplique uma política restritiva sem `unsafe-inline`.",
    },
    "headers.csp_report_only": {
        "title": "Política de conteúdo está em modo somente-relatório",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Apenas Content-Security-Policy-Report-Only foi retornado, sem um CSP aplicado.",
        "developer_impact": "Violações podem ser reportadas, mas o navegador não bloqueia conteúdo inseguro.",
        "remediation": "Use os relatórios para corrigir violações e depois implante a mesma política em Content-Security-Policy.",
    },
    "headers.csp_unsafe_inline": {
        "title": "CSP permite execução de script inline",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "O CSP aplicado contém `unsafe-inline`.",
        "developer_impact": "`unsafe-inline` enfraquece a proteção do CSP contra scripts injetados, anulando boa parte de seu propósito.",
        "remediation": "Substitua scripts inline por arquivos externos, ou autorize-os com nonces ou hashes.",
    },
    "headers.csp_unsafe_eval": {
        "title": "CSP permite avaliação dinâmica de código",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "O CSP aplicado contém `unsafe-eval`.",
        "developer_impact": "`unsafe-eval` permite APIs como eval(), aumentando o impacto de qualquer injeção de script.",
        "remediation": "Remova APIs do tipo eval e retire `unsafe-eval` de script-src.",
    },
    "headers.csp_wildcard": {
        "title": "CSP confia em uma origem coringa",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Uma diretiva do CSP aceita `*` como origem.",
        "developer_impact": "Confiança ampla em origens pode permitir que conteúdo de um host controlado por atacante seja carregado.",
        "remediation": "Substitua origens coringa pela menor lista explícita de permissões que a aplicação precisa.",
    },
    "headers.frame_options_missing": {
        "title": "Página pode ser incorporada em outro site",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-1021",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CLNT-09",
        "description": "Nem CSP frame-ancestors nem X-Frame-Options foram retornados.",
        "developer_impact": "Um atacante pode sobrepor esta página e induzir usuários a clicar em controles sensíveis (clickjacking).",
        "remediation": "Adicione `frame-ancestors 'none'` (ou origens confiáveis) ao Content-Security-Policy. X-Frame-Options: DENY é um fallback legado.",
    },
    "headers.nosniff_missing": {
        "title": "Navegador pode adivinhar o tipo de conteúdo da resposta",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "X-Content-Type-Options está ausente ou não é `nosniff`.",
        "developer_impact": "Conteúdo enviado ou servido com o tipo errado pode ser interpretado como conteúdo executável pelo navegador.",
        "remediation": "Retorne o Content-Type correto e adicione `X-Content-Type-Options: nosniff`.",
    },
    "headers.referrer_policy_missing": {
        "title": "URLs podem vazar pelo cabeçalho Referer",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Referrer-Policy está ausente.",
        "developer_impact": "Caminhos e parâmetros de query podem ser expostos a sites de terceiros quando usuários seguem links externos.",
        "remediation": "Adicione `Referrer-Policy: strict-origin-when-cross-origin` e nunca coloque segredos em URLs.",
    },
    "headers.permissions_policy_missing": {
        "title": "Capacidades do navegador não são explicitamente restringidas",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Permissions-Policy está ausente.",
        "developer_impact": "Conteúdo incorporado ou comprometido pode solicitar capacidades do navegador que a aplicação não precisa.",
        "remediation": "Adicione uma Permissions-Policy que desabilite recursos não utilizados, por exemplo `camera=(), microphone=(), geolocation=()`.",
    },
    "headers.coop_missing": {
        "title": "Janela de nível superior não está isolada",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Cross-Origin-Opener-Policy está ausente.",
        "developer_impact": "Sem COOP, janelas de origem cruzada podem manter referências que habilitam ataques de canal lateral ou baseados em opener.",
        "remediation": "Adicione `Cross-Origin-Opener-Policy: same-origin` após testar integrações e pop-ups de login.",
    },
    "headers.corp_missing": {
        "title": "Política de carregamento de recursos não é explícita",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Cross-Origin-Resource-Policy está ausente.",
        "developer_impact": "Outras origens podem conseguir incorporar este recurso, a menos que outro comportamento da aplicação impeça isso.",
        "remediation": "Para recursos não públicos, defina `Cross-Origin-Resource-Policy: same-origin` ou `same-site`.",
    },
    "headers.content_type_missing": {
        "title": "Resposta não possui tipo de conteúdo explícito",
        "category": "Cabeçalhos de Segurança",
        "cwe": "CWE-116",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Uma resposta que parece textual foi recebida sem o cabeçalho Content-Type.",
        "developer_impact": "Clientes e proxies intermediários podem interpretar a resposta de forma inconsistente.",
        "remediation": "Retorne um `Content-Type` explícito (por exemplo, `text/html; charset=UTF-8`) em toda resposta.",
    },
    "cookies.missing_secure": {
        "title": "Cookie pode ser enviado por conexão não criptografada",
        "category": "Gerenciamento de Sessão",
        "cwe": "CWE-614",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "Ao menos um cabeçalho Set-Cookie não possui o atributo Secure.",
        "developer_impact": "Um cookie de sessão ou autenticação sem Secure pode trafegar por HTTP e ser capturado na rede.",
        "remediation": "Defina o atributo `Secure` em todo cookie de sessão e autenticação.",
    },
    "cookies.missing_httponly": {
        "title": "JavaScript pode ler um cookie",
        "category": "Gerenciamento de Sessão",
        "cwe": "CWE-1004",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "Ao menos um cabeçalho Set-Cookie não possui HttpOnly.",
        "developer_impact": "Se existir uma falha de XSS em outro ponto, scripts podem roubar cookies que não possuem HttpOnly.",
        "remediation": "Defina `HttpOnly` em cookies que não precisam de acesso via JavaScript.",
    },
    "cookies.missing_samesite": {
        "title": "Cookie não possui política explícita entre sites",
        "category": "Gerenciamento de Sessão",
        "cwe": "CWE-352",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "Ao menos um cabeçalho Set-Cookie não possui SameSite.",
        "developer_impact": "O navegador pode incluir o cookie em requisições entre sites, aumentando a exposição a CSRF.",
        "remediation": "Defina `SameSite=Lax` ou `Strict`; use `None; Secure` somente quando o uso entre sites for necessário.",
    },
    "cookies.broad_domain": {
        "title": "Cookie é compartilhado com todos os subdomínios",
        "category": "Gerenciamento de Sessão",
        "cwe": "CWE-284",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "Ao menos um cabeçalho Set-Cookie inclui um atributo Domain explícito.",
        "developer_impact": "Um subdomínio comprometido ou menos confiável pode ler ou influenciar um cookie com escopo amplo.",
        "remediation": "Prefira cookies host-only omitindo Domain; considere o prefixo `__Host-` para cookies de sessão.",
    },
    "cookies.samesite_none_insecure": {
        "title": "Cookie SameSite=None está sem Secure",
        "category": "Gerenciamento de Sessão",
        "cwe": "CWE-614",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "Um cookie SameSite=None não define também Secure.",
        "developer_impact": "Navegadores modernos podem rejeitar o cookie completamente, e clientes mais antigos poderiam enviá-lo por HTTP simples.",
        "remediation": "Sempre que usar `SameSite=None`, defina também `Secure`.",
    },
    "cors.wildcard_origin": {
        "title": "CORS permite qualquer origem",
        "category": "Configuração Incorreta de CORS",
        "cwe": "CWE-942",
        "owasp": "A01:2025 Broken Access Control",
        "wstg": "WSTG-CLNT-07",
        "description": "Access-Control-Allow-Origin é `*` em uma requisição de baseline, sem autenticação.",
        "developer_impact": "Qualquer site pode ler esta resposta no lado do cliente quando o navegador permite a requisição entre origens.",
        "remediation": "Retorne Access-Control-Allow-Origin apenas para origens explicitamente confiáveis e adicione `Vary: Origin`.",
    },
    "cors.credentials_with_wildcard": {
        "title": "CORS combina credenciais com origem coringa",
        "category": "Configuração Incorreta de CORS",
        "cwe": "CWE-942",
        "owasp": "A01:2025 Broken Access Control",
        "wstg": "WSTG-CLNT-07",
        "description": "A resposta define tanto uma origem coringa quanto Access-Control-Allow-Credentials: true.",
        "developer_impact": "Navegadores devem rejeitar essa combinação, mas proxies ou mudanças de framework podem restringir silenciosamente a origem depois e expor dados autenticados.",
        "remediation": "Nunca combine CORS com credenciais e uma origem coringa; valide o Origin contra uma lista de permissões estrita.",
    },
    "cache.sensitive_no_store_missing": {
        "title": "Resposta potencialmente vinculada à sessão sem política no-store",
        "category": "Segurança de Cache",
        "cwe": "CWE-525",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "A resposta define cookies (ou varia por Authorization), mas Cache-Control não contém no-store.",
        "developer_impact": "Navegadores compartilhados, proxies ou CDNs podem reter uma resposta associada à sessão de um usuário específico.",
        "remediation": "Para respostas sensíveis e autenticadas, retorne `Cache-Control: no-store, private`.",
    },
    "disclosure.server_header": {
        "title": "Detalhes do servidor web são expostos",
        "category": "Exposição de Informações",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-02",
        "description": "O cabeçalho de resposta Server expõe informações de produto ou versão.",
        "developer_impact": "Indícios de versão ajudam atacantes a priorizar técnicas específicas do produto e CVEs conhecidas.",
        "remediation": "Remova detalhes de versão do cabeçalho Server no servidor web ou proxy reverso.",
    },
    "disclosure.powered_by_header": {
        "title": "Tecnologia da aplicação é exposta",
        "category": "Exposição de Informações",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-08",
        "description": "O cabeçalho de resposta X-Powered-By expõe detalhes de framework ou runtime.",
        "developer_impact": "A exposição de framework ou runtime facilita o fingerprinting automatizado e a exploração direcionada.",
        "remediation": "Desabilite o cabeçalho X-Powered-By (no PHP, defina `expose_php = Off`).",
    },
    "disclosure.stack_trace": {
        "title": "Erro detalhado da aplicação pode estar exposto",
        "category": "Exposição de Informações",
        "cwe": "CWE-209",
        "owasp": "A10:2025 Mishandling of Exceptional Conditions",
        "wstg": "WSTG-ERRH-01",
        "description": "O corpo da resposta corresponde a um padrão comum de stack trace, erro de banco de dados ou erro de runtime.",
        "developer_impact": "Stack traces revelam caminhos de código, queries, caminhos de arquivo e detalhes de implementação úteis para novos ataques.",
        "remediation": "Desabilite erros detalhados fora do ambiente de desenvolvimento, registre-os no servidor e retorne um identificador de requisição genérico ao cliente.",
    },
    "disclosure.directory_listing": {
        "title": "Listagem de diretório parece estar habilitada",
        "category": "Exposição de Informações",
        "cwe": "CWE-548",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-04",
        "description": "O título ou cabeçalho da página corresponde a um índice automático de diretório comum.",
        "developer_impact": "Visitantes podem enumerar backups, arquivos de código-fonte, logs ou outros arquivos que não deveriam ser públicos.",
        "remediation": "Desabilite a listagem automática de diretórios e exponha apenas recursos explicitamente roteados.",
    },
    "disclosure.source_map": {
        "title": "Resposta de produção anuncia um source map",
        "category": "Exposição de Informações",
        "cwe": "CWE-540",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "Um cabeçalho de source map ou referência `sourceMappingURL` está presente.",
        "developer_impact": "Source maps podem revelar o código-fonte original do frontend, nomes internos, comentários e endpoints não documentados.",
        "remediation": "Não publique source maps de produção publicamente, ou restrinja o acesso ao seu serviço de monitoramento.",
    },
    "disclosure.mixed_content": {
        "title": "Página HTTPS referencia recursos HTTP",
        "category": "Exposição de Informações",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "Um documento HTTPS referencia um recurso absoluto `http://` ou uma action de formulário.",
        "developer_impact": "Scripts, estilos, imagens ou frames não criptografados podem ser bloqueados ou modificados em trânsito.",
        "remediation": "Altere as URLs de recursos para HTTPS ou URLs relativas de mesma origem e adicione o CSP `upgrade-insecure-requests`.",
    },
    "disclosure.password_over_http": {
        "title": "Formulário de senha é entregue sem HTTPS",
        "category": "Exposição de Informações",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "Uma resposta HTTP contém um campo de entrada do tipo password.",
        "developer_impact": "Credenciais e a marcação do formulário podem ser interceptadas ou modificadas antes do envio.",
        "remediation": "Sirva todo o fluxo de login por HTTPS e redirecione o HTTP antes de renderizar qualquer formulário.",
    },
    "secrets.high_confidence_pattern": {
        "title": "Provável credencial ou chave privada exposta na resposta",
        "category": "Exposição de Segredos",
        "cwe": "CWE-798",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "O corpo da resposta contém texto que corresponde a um formato conhecido de credencial ou chave privada.",
        "developer_impact": "Uma chave, token ou chave privada exposta pode ser usada por qualquer pessoa que obtenha esta resposta para se passar pela aplicação ou acessar serviços internos.",
        "remediation": "Remova o segredo da resposta, revogue e rotacione imediatamente a credencial exposta, e carregue segredos apenas a partir de configuração no lado do servidor.",
    },
    "secrets.heuristic_pattern": {
        "title": "Possível valor semelhante a credencial na resposta",
        "category": "Exposição de Segredos",
        "cwe": "CWE-798",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "O corpo da resposta contém um valor de alta entropia, com nome de campo genérico, que se assemelha a uma credencial.",
        "developer_impact": "Se este valor for uma credencial real, qualquer pessoa que obtenha esta resposta poderia reutilizá-la.",
        "remediation": "Confirme se o valor é um segredo ativo; se for, remova-o da saída visível ao cliente e rotacione-o.",
    },
}
