"""Static reference text for passive checks: category, CWE, OWASP Top 10:2025, WSTG v4.2 id,
description, developer impact, and remediation. Severity and confidence are computed dynamically
by each plugin from the actual response and page context, never read from this table.
"""

CATALOG: dict[str, dict[str, str]] = {
    "transport.https": {
        "title": "Connection is not encrypted",
        "category": "Transport Security",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "The page was retrieved over plain HTTP instead of HTTPS.",
        "developer_impact": "Anyone on the network path may read or modify requests and responses, including credentials and session cookies.",
        "remediation": "Redirect every HTTP request to HTTPS and configure a valid TLS certificate.",
    },
    "tls.legacy_protocol": {
        "title": "Legacy TLS protocol is in use",
        "category": "Transport Security",
        "cwe": "CWE-326",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "The server negotiated a deprecated TLS version.",
        "developer_impact": "Older TLS versions contain known design weaknesses and may violate current compliance baselines.",
        "remediation": "Configure the server to allow TLS 1.2 and TLS 1.3 only.",
    },
    "tls.certificate_expiry": {
        "title": "TLS certificate expires soon",
        "category": "Transport Security",
        "cwe": "CWE-298",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "The TLS certificate's remaining lifetime is short.",
        "developer_impact": "An expired certificate causes browser warnings and can make the application unavailable.",
        "remediation": "Automate certificate renewal and alert before the remaining lifetime reaches 30 days.",
    },
    "headers.hsts_missing": {
        "title": "Browser can be downgraded to HTTP",
        "category": "Security Headers",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CONF-07",
        "description": "The HTTPS response does not send Strict-Transport-Security.",
        "developer_impact": "A first visit, or a link typed as http://, can still be intercepted before an HTTPS redirect runs.",
        "remediation": "On HTTPS responses, add `Strict-Transport-Security: max-age=31536000; includeSubDomains` after validating all subdomains.",
    },
    "headers.hsts_weak": {
        "title": "HSTS policy is too short",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CONF-07",
        "description": "Strict-Transport-Security is present but its max-age is short.",
        "developer_impact": "A short max-age gives downgrade protection only briefly, re-exposing users between visits.",
        "remediation": "After validating HTTPS coverage, increase HSTS max-age to at least 31536000 seconds.",
    },
    "headers.csp_missing": {
        "title": "Browser has no content execution policy",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "No Content-Security-Policy header was returned.",
        "developer_impact": "Injected scripts have fewer browser-level restrictions, increasing the impact of any XSS bug.",
        "remediation": "Start with a report-only Content-Security-Policy, inventory required origins, then enforce a restrictive policy without `unsafe-inline`.",
    },
    "headers.csp_report_only": {
        "title": "Content policy is report-only",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Only Content-Security-Policy-Report-Only was returned, no enforced CSP.",
        "developer_impact": "Violations may be reported, but the browser does not block unsafe content.",
        "remediation": "Use reports to fix violations, then deploy the same policy in Content-Security-Policy.",
    },
    "headers.csp_unsafe_inline": {
        "title": "CSP permits inline script execution",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "The enforced CSP contains `unsafe-inline`.",
        "developer_impact": "`unsafe-inline` weakens CSP protection against injected scripts, defeating much of its purpose.",
        "remediation": "Replace inline scripts with external files, or authorize them with nonces or hashes.",
    },
    "headers.csp_unsafe_eval": {
        "title": "CSP permits dynamic code evaluation",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "The enforced CSP contains `unsafe-eval`.",
        "developer_impact": "`unsafe-eval` allows APIs such as eval(), increasing the impact of any script injection.",
        "remediation": "Remove eval-like APIs and delete `unsafe-eval` from script-src.",
    },
    "headers.csp_wildcard": {
        "title": "CSP trusts a wildcard source",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "A CSP directive accepts `*` as a source.",
        "developer_impact": "Broad source trust can allow content from an attacker-controlled host to load.",
        "remediation": "Replace wildcard sources with the smallest explicit allowlist the application needs.",
    },
    "headers.frame_options_missing": {
        "title": "Page can potentially be embedded in another site",
        "category": "Security Headers",
        "cwe": "CWE-1021",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CLNT-09",
        "description": "Neither CSP frame-ancestors nor X-Frame-Options was returned.",
        "developer_impact": "An attacker may overlay this page and trick users into clicking sensitive controls (clickjacking).",
        "remediation": "Add `frame-ancestors 'none'` (or trusted origins) to Content-Security-Policy. X-Frame-Options: DENY is a legacy fallback.",
    },
    "headers.nosniff_missing": {
        "title": "Browser may guess response content types",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "X-Content-Type-Options is missing or not `nosniff`.",
        "developer_impact": "Content uploaded or served with the wrong type may be interpreted as executable content by the browser.",
        "remediation": "Return the correct Content-Type and add `X-Content-Type-Options: nosniff`.",
    },
    "headers.referrer_policy_missing": {
        "title": "URLs may leak through the Referer header",
        "category": "Security Headers",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Referrer-Policy is missing.",
        "developer_impact": "Paths and query parameters can be disclosed to third-party sites when users follow outbound links.",
        "remediation": "Add `Referrer-Policy: strict-origin-when-cross-origin` and never put secrets in URLs.",
    },
    "headers.permissions_policy_missing": {
        "title": "Browser capabilities are not explicitly restricted",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Permissions-Policy is missing.",
        "developer_impact": "Embedded or compromised content may request browser capabilities the application does not need.",
        "remediation": "Add a Permissions-Policy that disables unused features, e.g. `camera=(), microphone=(), geolocation=()`.",
    },
    "headers.coop_missing": {
        "title": "Top-level window is not isolated",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Cross-Origin-Opener-Policy is missing.",
        "developer_impact": "Without COOP, cross-origin windows may retain references that enable side-channel or opener-based attacks.",
        "remediation": "Add `Cross-Origin-Opener-Policy: same-origin` after testing integrations and sign-in popups.",
    },
    "headers.corp_missing": {
        "title": "Resource loading policy is not explicit",
        "category": "Security Headers",
        "cwe": "CWE-693",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "Cross-Origin-Resource-Policy is missing.",
        "developer_impact": "Other origins may be able to embed this resource unless other application behavior prevents it.",
        "remediation": "For non-public resources, set `Cross-Origin-Resource-Policy: same-origin` or `same-site`.",
    },
    "headers.content_type_missing": {
        "title": "Response has no explicit content type",
        "category": "Security Headers",
        "cwe": "CWE-116",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "A response that appears textual was received without a Content-Type header.",
        "developer_impact": "Clients and intermediate proxies may interpret the response inconsistently.",
        "remediation": "Return an explicit `Content-Type` (e.g. `text/html; charset=UTF-8`) on every response.",
    },
    "cookies.missing_secure": {
        "title": "Cookie can be sent over an unencrypted connection",
        "category": "Session Management",
        "cwe": "CWE-614",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "At least one Set-Cookie header lacks the Secure attribute.",
        "developer_impact": "A session or authentication cookie without Secure may travel over HTTP and be captured on the network.",
        "remediation": "Set the `Secure` attribute on every session and authentication cookie.",
    },
    "cookies.missing_httponly": {
        "title": "JavaScript can read a cookie",
        "category": "Session Management",
        "cwe": "CWE-1004",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "At least one Set-Cookie header lacks HttpOnly.",
        "developer_impact": "If an XSS issue exists elsewhere, scripts can steal cookies that lack HttpOnly.",
        "remediation": "Set `HttpOnly` on cookies that do not require JavaScript access.",
    },
    "cookies.missing_samesite": {
        "title": "Cookie has no explicit cross-site policy",
        "category": "Session Management",
        "cwe": "CWE-352",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "At least one Set-Cookie header lacks SameSite.",
        "developer_impact": "The browser may include the cookie in cross-site requests, increasing CSRF exposure.",
        "remediation": "Set `SameSite=Lax` or `Strict`; use `None; Secure` only when cross-site use is required.",
    },
    "cookies.broad_domain": {
        "title": "Cookie is shared with all subdomains",
        "category": "Session Management",
        "cwe": "CWE-284",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "At least one Set-Cookie header includes an explicit Domain attribute.",
        "developer_impact": "A compromised or less-trusted subdomain may read or influence a broadly scoped cookie.",
        "remediation": "Prefer host-only cookies by omitting Domain; consider the `__Host-` prefix for session cookies.",
    },
    "cookies.samesite_none_insecure": {
        "title": "SameSite=None cookie is missing Secure",
        "category": "Session Management",
        "cwe": "CWE-614",
        "owasp": "A07:2025 Authentication Failures",
        "wstg": "WSTG-SESS-02",
        "description": "A SameSite=None cookie does not also set Secure.",
        "developer_impact": "Modern browsers may reject the cookie outright, and older clients could send it over plain HTTP.",
        "remediation": "Whenever using `SameSite=None`, also set `Secure`.",
    },
    "cors.wildcard_origin": {
        "title": "CORS allows every origin",
        "category": "CORS Misconfiguration",
        "cwe": "CWE-942",
        "owasp": "A01:2025 Broken Access Control",
        "wstg": "WSTG-CLNT-07",
        "description": "Access-Control-Allow-Origin is `*` on a baseline, unauthenticated request.",
        "developer_impact": "Any website can read this response client-side when the browser permits the cross-origin request.",
        "remediation": "Return Access-Control-Allow-Origin only for explicitly trusted origins and add `Vary: Origin`.",
    },
    "cors.credentials_with_wildcard": {
        "title": "CORS combines credentials with a wildcard origin",
        "category": "CORS Misconfiguration",
        "cwe": "CWE-942",
        "owasp": "A01:2025 Broken Access Control",
        "wstg": "WSTG-CLNT-07",
        "description": "The response sets both a wildcard origin and Access-Control-Allow-Credentials: true.",
        "developer_impact": "Browsers must reject this combination, but proxies or framework changes can silently narrow the origin later and expose authenticated data.",
        "remediation": "Never combine credentialed CORS with a wildcard; validate the Origin against a strict allowlist instead.",
    },
    "cache.sensitive_no_store_missing": {
        "title": "Potentially session-aware response lacks a no-store policy",
        "category": "Cache Security",
        "cwe": "CWE-525",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-12",
        "description": "The response sets cookies (or varies on Authorization) but Cache-Control does not contain no-store.",
        "developer_impact": "Shared browsers, proxies, or CDNs may retain a response associated with a specific user's session.",
        "remediation": "For sensitive authenticated responses, return `Cache-Control: no-store, private`.",
    },
    "disclosure.server_header": {
        "title": "Web server details are exposed",
        "category": "Information Disclosure",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-02",
        "description": "The Server response header discloses product or version information.",
        "developer_impact": "Version hints help attackers prioritize product-specific techniques and known CVEs.",
        "remediation": "Remove version details from the Server header at the web server or reverse proxy.",
    },
    "disclosure.powered_by_header": {
        "title": "Application technology is exposed",
        "category": "Information Disclosure",
        "cwe": "CWE-200",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-08",
        "description": "The X-Powered-By response header discloses framework or runtime details.",
        "developer_impact": "Framework or runtime disclosure makes automated fingerprinting and targeted exploitation easier.",
        "remediation": "Disable the X-Powered-By header (for PHP, set `expose_php = Off`).",
    },
    "disclosure.stack_trace": {
        "title": "Detailed application error may be exposed",
        "category": "Information Disclosure",
        "cwe": "CWE-209",
        "owasp": "A10:2025 Mishandling of Exceptional Conditions",
        "wstg": "WSTG-ERRH-01",
        "description": "The response body matches a common stack trace, database, or runtime error pattern.",
        "developer_impact": "Stack traces reveal code paths, queries, file paths, and implementation details useful for further attacks.",
        "remediation": "Disable detailed errors outside development, log them server-side, and return a generic request identifier to the client.",
    },
    "disclosure.directory_listing": {
        "title": "Directory listing appears to be enabled",
        "category": "Information Disclosure",
        "cwe": "CWE-548",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-CONF-04",
        "description": "The page title or heading matches a common automatic directory index.",
        "developer_impact": "Visitors may enumerate backups, source files, logs, or other files that were not intended to be public.",
        "remediation": "Disable automatic directory indexes and expose only explicitly routed resources.",
    },
    "disclosure.source_map": {
        "title": "Production response advertises a source map",
        "category": "Information Disclosure",
        "cwe": "CWE-540",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "A source-map header or `sourceMappingURL` reference is present.",
        "developer_impact": "Source maps can reveal original frontend source, internal names, comments, and undocumented endpoints.",
        "remediation": "Do not publish production source maps publicly, or restrict access to your monitoring service.",
    },
    "disclosure.mixed_content": {
        "title": "HTTPS page references HTTP resources",
        "category": "Information Disclosure",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "An HTTPS document references an absolute `http://` resource or form action.",
        "developer_impact": "Unencrypted scripts, styles, images, or frames can be blocked or modified in transit.",
        "remediation": "Change resource URLs to HTTPS or same-origin relative URLs and add CSP `upgrade-insecure-requests`.",
    },
    "disclosure.password_over_http": {
        "title": "Password form is delivered without HTTPS",
        "category": "Information Disclosure",
        "cwe": "CWE-319",
        "owasp": "A04:2025 Cryptographic Failures",
        "wstg": "WSTG-CRYP-01",
        "description": "An HTTP response contains a password input field.",
        "developer_impact": "Credentials and form markup can be intercepted or modified before submission.",
        "remediation": "Serve the entire sign-in flow over HTTPS and redirect HTTP before rendering any form.",
    },
    "secrets.high_confidence_pattern": {
        "title": "Likely credential or private key exposed in response",
        "category": "Secrets Exposure",
        "cwe": "CWE-798",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "The response body contains text matching a well-known credential or private-key format.",
        "developer_impact": "An exposed key, token, or private key can be used by anyone who fetches this response to impersonate the application or access backing services.",
        "remediation": "Remove the secret from the response, rotate the exposed credential immediately, and load secrets from server-side configuration only.",
    },
    "secrets.heuristic_pattern": {
        "title": "Possible credential-like value in response",
        "category": "Secrets Exposure",
        "cwe": "CWE-798",
        "owasp": "A02:2025 Security Misconfiguration",
        "wstg": "WSTG-INFO-05",
        "description": "The response body contains a generically named, high-entropy value that resembles a credential.",
        "developer_impact": "If this value is a live credential, anyone who fetches this response could reuse it.",
        "remediation": "Confirm whether the value is a live secret; if so, remove it from client-visible output and rotate it.",
    },
}
