<?php
require __DIR__.'/../app/bootstrap.php';
$page=$_GET['page']??'home';
try {
if($_SERVER['REQUEST_METHOD']==='POST'){
    checkCsrf();
    if($page==='create'){
        $name=trim($_POST['name']??'');$url=trim($_POST['url']??'');$scheme=parse_url($url,PHP_URL_SCHEME);
        if($name===''||!filter_var($url,FILTER_VALIDATE_URL)||!in_array($scheme,['http','https'],true)||!isset($_POST['authorized']))throw new InvalidArgumentException('Enter a name, a valid HTTP(S) URL, and confirm authorization.');
        db()->prepare('INSERT INTO applications(name,base_url,authorization_confirmed_at) VALUES(?,?,UTC_TIMESTAMP())')->execute([$name,$url]);
        $_SESSION['notice']='Application registered.';go('index.php');
    }
    if($page==='run'){
        $app=one('SELECT * FROM applications WHERE id=?',[(int)($_POST['application_id']??0)]);if(!$app)throw new InvalidArgumentException('Application not found.');
        db()->prepare("INSERT INTO analyses(application_id,status) VALUES(?,'running')")->execute([$app['id']]);$id=(int)db()->lastInsertId();$result=scanner($app['base_url']);
        if(empty($result['ok'])){db()->prepare("UPDATE analyses SET status='failed',error_message=?,completed_at=UTC_TIMESTAMP() WHERE id=?")->execute([$result['error']??'Unknown error',$id]);go('index.php?page=result&id='.$id);}
        db()->beginTransaction();$insert=db()->prepare('INSERT INTO findings(analysis_id,fingerprint,title,category,cwe,owasp,wstg,severity,confidence,status,description,evidence_summary,affected_url,method,parameter,parameter_location,evidence,developer_impact,remediation,manual_review_required) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
        foreach($result['findings'] as $f)$insert->execute([$id,$f['fingerprint'],$f['title'],$f['category']??null,$f['cwe']??null,$f['owasp']??null,$f['wstg']??null,$f['severity'],$f['confidence']??null,$f['status']??null,$f['description']??null,$f['evidence_summary']??null,$f['affected_url'],$f['method']??null,$f['parameter']??null,$f['parameter_location']??null,json_encode($f['evidence']??[],JSON_UNESCAPED_SLASHES),$f['developer_impact'],$f['remediation'],!empty($f['manual_review_required'])?1:0]);
        db()->prepare("UPDATE analyses SET status='completed',security_score=?,checks_run=?,duration_ms=?,http_status=?,completed_at=UTC_TIMESTAMP() WHERE id=?")->execute([calculateScore($result['findings']),(int)$result['checks_run'],(int)$result['duration_ms'],(int)$result['status_code'],$id]);db()->commit();go('index.php?page=result&id='.$id);
    }
}
if($page==='add'){
    page('Add application','<section class="intro compact"><p class="eyebrow">AUTHORIZED TARGET</p><h1>Register an application</h1><p>The scanner sends one read-only GET request. Only scan targets you own or are authorized to assess.</p></section><form class="card form" method="post" action="index.php?page=create"><input type="hidden" name="csrf" value="'.csrf().'"><label>Application name<input name="name" maxlength="120" required placeholder="Customer Portal"></label><label>Base URL<input name="url" type="url" required placeholder="https://staging.example.com/"></label><label class="check"><input type="checkbox" name="authorized" value="1" required><span>I confirm that I own this target or have explicit authorization.</span></label><button>Register application</button></form>');exit;
}
if($page==='result'||$page==='report'){
    $a=analysis((int)($_GET['id']??0));if(!$a)throw new InvalidArgumentException('Analysis not found.');$rows=findings((int)$a['id']);$list='';
    foreach($rows as $f)$list.=renderFinding($f);
    $buttons=$page==='report'?'<button onclick="print()">Print / Save as PDF</button>':'<a class="button secondary" href="index.php?page=report&id='.$a['id'].'">Printable report</a>';
    $body='<div class="toolbar no-print"><a href="index.php">&larr; Dashboard</a>'.$buttons.'</div><section class="result-header"><div><p class="eyebrow">ANALYSIS #'.(int)$a['id'].'</p><h1>'.e($a['application_name']).'</h1><p>'.e($a['base_url']).' &middot; '.e($a['completed_at']??$a['started_at']).' UTC</p></div><div class="score"><strong>'.($a['security_score']??'N/A').'</strong><span>Security Score</span></div></section>';
    if($a['status']==='failed')$body.='<div class="error"><b>The analysis could not complete.</b><br>'.e($a['error_message']).'</div>';else $body.='<div class="metrics"><div><span>Checks run</span><b>'.(int)$a['checks_run'].'</b></div><div><span>Findings</span><b>'.count($rows).'</b></div><div><span>HTTP status</span><b>'.(int)$a['http_status'].'</b></div><div><span>Duration</span><b>'.(int)$a['duration_ms'].' ms</b></div></div><h2>What your team should address</h2>'.($list !== '' ? $list : '<div class="empty">No issues were detected by the configured checks.</div>').'<section class="limitations"><h2>Scope and limitations</h2><p>This passive assessment is a development aid. It does not exploit the target, prove the absence of vulnerabilities, or replace a professional penetration test.</p></section>';
    page($page==='report'?'Security report':'Analysis result',$body);exit;
}
if($page==='compare'){
    $old=analysis((int)($_GET['old']??0));$new=analysis((int)($_GET['new']??0));if(!$old||!$new||$old['application_id']!==$new['application_id'])throw new InvalidArgumentException('Choose analyses from the same application.');$left=array_column(findings((int)$old['id']),null,'fingerprint');$right=array_column(findings((int)$new['id']),null,'fingerprint');
    $section=function(string $title,array $rows,string $type){$html='<section class="card"><h2>'.$title.' <small>'.count($rows).'</small></h2>';foreach($rows as $r)$html.='<div class="compare '.$type.'"><b>'.e($r['title']).'</b><span>'.e($r['severity']).'</span></div>';return $html.'</section>';};
    page('Comparison','<div class="toolbar"><a href="index.php">← Dashboard</a></div><h1>What changed?</h1><p>Analysis #'.$old['id'].' → #'.$new['id'].' · Score '.$old['security_score'].' → '.$new['security_score'].'</p><div class="comparison">'.$section('New issues',array_diff_key($right,$left),'new').$section('Still present',array_intersect_key($right,$left),'same').$section('Fixed',array_diff_key($left,$right),'fixed').'</div>');exit;
}
if($page==='about'){page('About','<section class="intro"><p class="eyebrow">BUILT FOR DEVELOPERS</p><h1>Security findings you can turn into code changes.</h1><p>SentinelScope translates passive HTTP observations into plain-language impact and practical remediation. It preserves evidence and progress without attempting exploitation.</p></section>');exit;}
$apps=all('SELECT a.*,COUNT(n.id) analysis_count FROM applications a LEFT JOIN analyses n ON n.application_id=a.id GROUP BY a.id ORDER BY a.created_at DESC');$cards='';
foreach($apps as $app){$history=all('SELECT * FROM analyses WHERE application_id=? ORDER BY started_at DESC',[$app['id']]);$options='';$table='';foreach($history as $h){$options.='<option value="'.$h['id'].'">#'.$h['id'].' · '.e($h['started_at']).'</option>';$table.='<tr><td><a href="index.php?page=result&id='.$h['id'].'">#'.$h['id'].'</a></td><td>'.e($h['started_at']).'</td><td>'.e($h['status']).'</td><td>'.($h['security_score']??'—').'</td><td>'.(int)($h['checks_run']??0).'</td></tr>';}$compare=count($history)>1?'<form class="compare-form" action="index.php"><input type="hidden" name="page" value="compare"><select name="old">'.$options.'</select><span>to</span><select name="new">'.$options.'</select><button class="secondary">Compare</button></form>':'';$cards.='<section class="card"><div class="app-head"><div><h2>'.e($app['name']).'</h2><p>'.e($app['base_url']).'</p></div><form method="post" action="index.php?page=run"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="application_id" value="'.$app['id'].'"><button>Run analysis</button></form></div>'.$compare.($table?'<div class="scroll"><table><thead><tr><th>ID</th><th>Date (UTC)</th><th>Status</th><th>Score</th><th>Checks</th></tr></thead><tbody>'.$table.'</tbody></table></div>':'<p class="muted">No analyses yet.</p>').'</section>';}
page('Dashboard','<section class="intro"><p class="eyebrow">DEVELOPER SECURITY WORKBENCH</p><h1>Find the risk.<br><span>Ship the fix.</span></h1><p>Run authorized, non-destructive checks and receive evidence your development team can understand and act on.</p><a class="button" href="index.php?page=add">Add an application</a></section><div class="section-head"><h2>Applications</h2><span>'.count($apps).' registered</span></div>'.($cards !== '' ? $cards : '<div class="empty">No applications registered yet.</div>'));
} catch(Throwable $error){if(db()->inTransaction())db()->rollBack();http_response_code(400);page('Error','<div class="error"><b>Request could not be completed.</b><br>'.e($error->getMessage()).'</div><a href="index.php">Return to dashboard</a>');}
